crypt_salt: REPLACE_WITH_RANDOM_VALUE
encryption_key: ADMIN123
exfil_dir: data/exfil
objects.planners.default: atomic
plugins:
- access
- atomic
- response
- stockpile
- emu
reachable_host_traits:
- remote.host.fqdn
- remote.host.ip
reports_dir: reports
